model:
  name: Snowflake/snowflake-arctic-embed-m
  num_labels: 6
  classifier_dropout: 0.0
  hidden_dropout_prob: 0.0
  output_hidden_states: false

tokenizer:
    pretrained_model_name_or_path: ${model.name}
    truncation: true
    padding: true
    max_length: 512
    special_tokens: null

data: 
  train_file_path: data/annotated_fineweb_multi_train_1k.jsonl
  train_file_split: train
  test_file_path: data/annotated_fineweb_multi_test_1k.jsonl # currently not used
  test_file_split: train # currently not used
  val_file_path: data/annotated_fineweb_multi_val_1k.jsonl
  val_file_split: train
  label_column: scores
  text_column: text
  num_metrics: 4
  num_classes_per_metric: [6, 6, 6, 2]
  
training:
  batch_size: 32
  epochs: 10
  use_bf16: true
  weight_decay: 0.01
  eval_strategy: epoch
  save_strategy: epoch
  logging_steps: 100
  seed: 42
  greater_is_better: false
  logging_dir_path: data/output/annotated_fineweb_model
  output_dir_path: data/output/annotated_fineweb_model