model:
  name: FacebookAI/xlm-roberta-base
  num_labels: 6
  classifier_dropout: 0.0
  hidden_dropout_prob: 0.0
  output_hidden_states: false

tokenizer:
    pretrained_model_name_or_path: ${model.name}
    truncation: true
    padding: true
    max_length: 512
    special_tokens: null

data: 
  train_file_path: data/annotated_fineweb_multi_train.jsonl
  train_file_split: train
  test_file_path: data/annotated_fineweb_multi_test.jsonl # currently not used
  test_file_split: train # currently not used
  val_file_path: data/annotated_fineweb_multi_val.jsonl
  val_file_split: train
  gt_file_path: null # ground truth data; can be null (optional)
  gt_file_split: train
  label_column: scores
  text_column: text
  num_regressor_outputs: 4
  num_classes_per_output: [6, 6, 6, 2]
  output_names: ["score", "score_transform_1", "score_transform_2", "score_transform_3"]
  
training:
  batch_size: 32
  epochs: 10
  use_bf16: true
  weight_decay: 0.01
  eval_strategy: epoch
  save_strategy: epoch
  logging_steps: 100
  regression_loss: true
  seed: 42
  greater_is_better: false
  metric_for_best_model: eval_loss
  learning_rate: 0.00001
  logging_dir_path: data/output/preliminary_xlm_roberta_base_regression
  output_dir_path: data/output/preliminary_xlm_roberta_base_regression
