model:
  name: Snowflake/snowflake-arctic-embed-m
  num_labels: 1
  classifier_dropout: 0.0
  hidden_dropout_prob: 0.0
  output_hidden_states: false

tokenizer:
    pretrained_model_name_or_path: ${model.name}
    truncation: false
    padding: false
    max_length: 512
    special_tokens: null

data: 
  train_file_path: ../data/datasets/lorem_ipsum_train.jsonl
  test_file_path: ../data/datasets/lorem_ipsum_test.jsonl
  val_file_path: ../data/datasets/lorem_ipsum_val.jsonl
  label_column: score
  text_column: text
  
training:
  batch_size: 32
  epochs: 10
  use_bf16: true
  weight_decay: 0.01
  eval_strategy: epoch
  save_strategy: epoch
  logging_steps: 100
  logging_dir_path: ../data/output/lorem_ipsum_model
  output_dir_path: ../data/output/lorem_ipsum_model