model:
  name: snowflake/snowflake-arctic-embed-m-v2.0 # check model
  loading_params:          
    unpad_inputs: true
    add_pooling_layer: false
    use_memory_efficient_attention: true
    trust_remote_code: true
  freeze_base_model_parameters: true  # Add option to freeze encoder
  num_tasks: ${data.num_tasks}  # Number of prediction tasks
  num_targets_per_task: ${data.num_targets_per_task}  # Number of classes per output
  is_regression: ${training.is_regression}
  regressor_hidden_dim: 1000

tokenizer:
  pretrained_model_name_or_path: ${model.name}
  truncation: true
  padding: longest
  max_length: 8192 # Check this
  add_generation_prompt: false

data: 
  train_file_path: /home/abbas-khan/processed_data_natural/training_set # /raid/s3/opengptx/jude/repos/ml_filter/data/sampled_data/final_dataset/training_set # /raid/s3/opengptx/jude/repos/ml_filter/data/sampled_data/data_training/training_set  # /home/alex-jude/training_set
  train_file_split: train
  test_file_path: /raid/s3/opengptx/jude/repos/ml_filter/data/ground_truth_511
  test_file_split: train
  val_file_path: /home/abbas-khan/processed_data_natural/validation_set # /raid/s3/opengptx/jude/repos/ml_filter/data/sampled_data/final_dataset/validation_set # /raid/s3/opengptx/jude/repos/ml_filter/data/sampled_data/data_training/validation_set  # /home/alex-jude/validation_set
  val_file_split: train
  label_column: score  # Ensure this matches dataset format
  text_column: text  # Ensure this matches dataset format
  document_id_column: id  # Ensure this matches dataset format
  num_tasks: 1
  num_targets_per_task: [6]
  task_names: ["edu"]
  num_processes: 64

training:
  batch_size: 512
  eval_batch_size: 512 # 1024
  epochs: 20
  use_bf16: true
  weight_decay: 0.01 # 0.01
  eval_strategy: steps
  save_strategy: "no"
  logging_steps: 10
  seed: 42
  is_regression: true
  greater_is_better: false  # Save model with lowest loss
  metric_for_best_model: eval_val_loss
  learning_rate: 5e-04 # 5e-04
  logging_dir_path: data/output/fineweb_edu_model_artic_v1_m_test_100_epoch
  output_dir_path: ${training.logging_dir_path}
  dataloader_num_workers: 16
  load_best_model_at_end: false
  wandb_run_name:  regression_trainer

embedding:
  normalize_embeddings: true
  init_regression_weights: false
  save_path: /home/abbas-khan/ml_filter/data/output/embeddings/new_embeddings.h5
  load_path: /home/abbas-khan/ml_filter/data/output/embeddings/embeddings.h5
