model:
  num_tasks: ${data.num_tasks}  # Number of prediction tasks
  num_targets_per_task: ${data.num_targets_per_task}  # Number of classes per output
  regressor_hidden_dim: 1000
  init_regression_weights: false

data: 
  train_file_path: /home/abbas-khan/embedding_output_Qwen_8k/training_embeddings
  train_file_split: train
  test_file_path: /home/abbas-khan/embedding_output_Qwen_8k/test_embeddings/
  test_file_split: train
  val_file_path: /home/abbas-khan/embedding_output_Qwen_8k/validation_embeddings
  embeddings_dataset: embeddings  # Name of the HDF5 dataset containing embedding vectors
  labels_dataset: labels  # Name of the HDF5 dataset containing labels
  num_tasks: 1
  num_targets_per_task: [6]
  task_names: ["edu"]
  num_processes: 64

training:
  batch_size: 1024
  eval_batch_size: 1024 # 1024
  epochs: 20
  use_bf16: true
  weight_decay: 0.01 # 0.01
  eval_strategy: epoch
  save_strategy: "no"
  logging_steps: 100
  seed: 42
  greater_is_better: true  # Spearman correlation is maximised
  metric_for_best_model: eval_test_edu/spearman_corr
  loss_reduction: mean  # Options: mean, sum, none
  learning_rate: 5e-04 # 5e-04
  logging_dir_path: data/output/fineweb_edu_model_artic_v1_m_test_100_epoch
  output_dir_path: ${training.logging_dir_path}
  dataloader_num_workers: 16
  load_best_model_at_end: false
  wandb_run_name:  regression_trainer
