model:
  num_tasks: ${data.num_tasks}  # Number of prediction tasks
  num_targets_per_task: ${data.num_targets_per_task}  # Number of classes per output
  is_regression: ${training.is_regression}
  regressor_hidden_dim: 1000
  init_regression_weights: false

tokenizer:
  pretrained_model_name_or_path: ${model.name}
  truncation: true
  padding: longest
  max_length: 8192 # Check this
  add_generation_prompt: true

data: 
  train_file_path: /home/abbas-khan/datatrove_embeddings/medium_model/snowflake-arctic-embed-m-v2.0_training_set_embeddings 
  train_file_split: train
  test_file_path: /home/abbas-khan/datatrove_embeddings/medium_model/snowflake-arctic-embed-m-v2.0_ground_truth_511_embeddings
  test_file_split: train
  val_file_path: /home/abbas-khan/datatrove_embeddings/medium_model/snowflake-arctic-embed-m-v2.0_validation_set_embeddings 
  label_column: score  # Ensure this matches dataset format
  text_column: text  # Ensure this matches dataset format
  document_id_column: id  # Ensure this matches dataset format
  num_tasks: 1
  num_targets_per_task: [6]
  task_names: ["edu"]
  num_processes: 64

training:
  batch_size: 1024
  eval_batch_size: 1024 # 1024
  epochs: 20
  use_bf16: true
  weight_decay: 0.01 # 0.01
  eval_strategy: epoch
  save_strategy: "no"
  logging_steps: 100
  seed: 42
  is_regression: true
  greater_is_better: yes  # Save model with lowest loss
  metric_for_best_model: test_edu/spearman_corr
  #metric_for_best_model: validation_edu/spearman_corr
  learning_rate: 5e-04 # 5e-04
  logging_dir_path: data/output/fineweb_edu_model_artic_v1_m_test_100_epoch
  output_dir_path: ${training.logging_dir_path}
  dataloader_num_workers: 16
  load_best_model_at_end: false
  wandb_run_name:  regression_trainer
