dataset_name: training

params:
  # File selection
  glob_pattern: "**/*.jsonl"
  input_dir: /data/horse/ws/alju972f-tokenization_at_scale/data_ml_filter/input

  # Output
  output_dir: /data/horse/ws/alju972f-tokenization_at_scale/data_ml_filter/embedding
  keys_to_index: ["id", "aggregation_type"]
  text_field: text
  embedding_dir: ${dataset_name}_embeddings
  compression: null

  # Precision
  embedding_dtype: float32
  label_dtype: int8
  model_dtype: bfloat16

  # Metadata key customization
  embedding_key: embeddings
  label_key: labels
  document_id_key: document_ids

  # Model and embedding parameters
  embedding_model: Snowflake/snowflake-arctic-embed-m-v2.0
  batch_size: 512
  writer_batch_size: 1000
  hdf5_dataset_name: train
  save_labels: false
  max_length: 8192
  padding: true
  truncation: true

running_on_slurm: true

local_settings: null

slurm_settings:
  sbatch_args:
    account: "p_gptx"
    nodes: 1
    ntasks: 1
    gres: gpu:1
  partition: "capella"
  time: "04:00:00"
  cpus_per_task: 8
  mem_per_cpu_gb: 2
  job_name: "MMbert_embedder"
  output: ${params.output_dir}/logs/%j.out
  error: ${params.output_dir}/logs/%j.err
  qos: "normal"
  venv_path: /data/cat/ws/alju972f-regression_heads/repos/env/jql_pipeline/bin/activate
  tasks: 1
  workers: 1
