embeddings_directory: /raid/s3/opengptx/jude/repos/ml_filter/data/embedding_output_dir/embeddings
output_dir: /raid/s3/opengptx/jude/repos/ml_filter/data/embedding_output_dir/annotations/

regression_head_checkpoints:
  Gemma_Snowflake: /raid/s3/opengptx/jude/repos/ml_filter/hessanAI/checkpoints/checkpoints/edu-gemma-snowflake-balanced.ckpt
  Llama_Snowflake: /raid/s3/opengptx/jude/repos/ml_filter/hessanAI/checkpoints/checkpoints/edu-llama-snowflake-balanced.ckpt
batch_size: 1000

tasks: 1
local_tasks: 1
local_rank_offset: 0
