dataset_name: training

params:
  # File selection
  glob_pattern: "**/*.jsonl"
  input_dir: /home/abbas-khan/processed_data_natural/${dataset_name}_set
  csv_hashmap_path: /home/abbas-khan/ml_filter/data/output/hashes/${dataset_name}.csv

  # Output
  output_dir: /home/abbas-khan/ml_filter/data/test/
  embedding_dir: ${dataset_name}_embeddings

  # Model and embedding parameters
  embedding_model: Qwen/Qwen3-Embedding-0.6B
  batch_size: 16
  writer_batch_size: 1000
  hdf5_dataset_name: train
  save_labels: true
  max_length: 8192
  padding: true
  truncation: true

running_on_slurm: false

local_settings:
  tasks: 2
  workers: 2
  local_tasks: 2
  local_rank_offset: 0

slurm_settings: null
