glob_pattern: "*.jsonl"
input_dir: /leonardo_work/EUHPC_D21_101/alexj/repos/ml_filter_outputs/trail_run/input_data_test
output_dir: /leonardo_work/EUHPC_D21_101/alexj/repos/ml_filter_outputs/trail_run/output_dir
csv_hashmap_path: /leonardo_work/EUHPC_D21_101/alexj/repos/scripts/hashes.csv

embedding_model: Snowflake/snowflake-arctic-embed-m-v2.0
batch_size: 1000

hdf5_dataset_name: train


slurm:
  partition: "boost_usr_prod"
  tasks: 1
  workers: 1001
  time: "01:00:00"
  cpus_per_task: 32
  gpus_per_task: 1
  mem_per_gpu: "8G"
  job_name: "lorem_ipsum_embedding"
  output: /leonardo_work/EUHPC_D21_101/alexj/repos/ml_filter_outputs/trail_run/output_dir/%j.out
  error: /leonardo_work/EUHPC_D21_101/alexj/repos/ml_filter_outputs/trail_run/output_dir/%j.err
  account: "EUHPC_E05_119"
  qos: "normal"
  nodes: 1
  ntasks_per_node: 1
  gres: gpu:1
  venv_path: /leonardo_work/EUHPC_D21_101/alexj/repos/scripts/env/env_annotation_pipeline/bin/activate