params:
  embeddings_directory: /raid/s3/opengptx/jude/repos/ml_filter/data/throughput_analysis/output/validation_embeddings
  output_dir: /raid/s3/opengptx/jude/repos/ml_filter/data/throughput_analysis/output/annotations

  regression_head_checkpoints:
    Gemma_Snowflake: /raid/s3/opengptx/jude/repos/ml_filter/hessanAI/checkpoints/checkpoints/edu-gemma-snowflake-balanced.ckpt
    Llama_Snowflake: /raid/s3/opengptx/jude/repos/ml_filter/hessanAI/checkpoints/checkpoints/edu-llama-snowflake-balanced.ckpt
    Mistral_Snowflake: /raid/s3/opengptx/jude/repos/ml_filter/hessanAI/checkpoints/checkpoints/edu-mistral-snowflake-balanced.ckpt
  batch_size: 1000
  hdf5_dataset_name: train
  output_keys: ["document_id", "score_Gemma_Snowflake", "score_Llama_Snowflake", "score_Mistral_Snowflake"]
  model_dtype: bfloat16
  embedding_dtype: bfloat16
  label_dtype: bfloat16
  compression: gzip
running_on_slurm: false

local_settings:
  tasks: 1
  workers: 1
  local_tasks: 1
  local_rank_offset: 0
  logging_dir: ${params.output_dir}/logs

slurm_settings: null
