dataset_name: validation

params:
  # File selection
  glob_pattern: "**/*.jsonl"
  input_dir: /raid/s3/opengptx/abbas/processed_data_natural/${dataset_name}_set
  csv_hashmap_path: /raid/s3/opengptx/jude/repos/ml_filter/embedding_ablations/dataset/hashes/${dataset_name}.csv

  # Output
  output_dir: /raid/s3/opengptx/jude/repos/ml_filter/embedding_ablations/mmbert_results/embeddings
  embedding_dir: ${dataset_name}_embeddings

  # Model and embedding parameters
  embedding_model: jhu-clsp/mmBERT-base
  batch_size: 128
  writer_batch_size: 1000
  hdf5_dataset_name: train
  save_labels: true
  max_length: 8192
  padding: true
  truncation: true

running_on_slurm: false

local_settings:
  tasks: 2
  workers: 2
  local_tasks: 2
  local_rank_offset: 0

slurm_settings: null
