embeddings_directory: /data/cat/ws/alju972f-annotation_at_scale/data/embedding_output_dir/embeddings
output_dir: /data/cat/ws/alju972f-annotation_at_scale/data/embedding_output_dir/annotations/

regression_head_checkpoints:
  Gemma_Snowflake: /data/cat/ws/alju972f-annotation_at_scale/data/embedding_output_dir/regression_heads/checkpoints/edu-gemma-snowflake-balanced.ckpt
  Llama_Snowflake: /data/cat/ws/alju972f-annotation_at_scale/data/embedding_output_dir/regression_heads/checkpoints/edu-llama-snowflake-balanced.ckpt
batch_size: 1000


slurm:
  partition: "capella"
  tasks: 1
  workers: 1001
  time: "01:00:00"
  cpus_per_task: 56
  gpus_per_task: 1
  mem_per_gpu: "8G"
  job_name: "lorem_ipsum_embedding"
  output: /data/cat/ws/alju972f-annotation_at_scale/.vscode/data/embedding_output_dir/scripts/slurm_output/%j.out
  error: /data/cat/ws/alju972f-annotation_at_scale/.vscode/data/embedding_output_dir/scripts/slurm_output/%j.err
  account: "p_gptx"
  qos: "normal"
  nodes: 4
  ntasks_per_node: 1
  gres: gpu:4