dataset_name: training

params:
  # File selection
  glob_pattern: "**/*.jsonl"
  input_dir: /data/cat/ws/alju972f-regression_heads/dataset/Regression_head/abbas/processed_data_natural/${dataset_name}_set
  csv_hashmap_path: /data/cat/ws/alju972f-regression_heads/dataset/Regression_head/abbas/hashes/${dataset_name}.csv

  # Output
  output_dir: /data/cat/ws/alju972f-regression_heads/dataset/mmbet_embeddings/test_set
  embedding_dir: ${dataset_name}_embeddings
  keys_to_index: ["id", "aggregation_type"]

  # Model and embedding parameters
  embedding_model: jhu-clsp/mmBERT-base
  batch_size: 16
  writer_batch_size: 1000
  hdf5_dataset_name: train
  save_labels: true
  max_length: 8192
  padding: true
  truncation: true

running_on_slurm: true

local_settings: null

slurm_settings:
  sbatch_args:
    account: "p_gptx"
    nodes: 1
    ntasks: 1
    gres: gpu:1
  partition: "capella"
  time: "04:00:00"
  cpus_per_task: 8
  mem_per_cpu_gb: 2
  gpus_per_task: 1
  job_name: "MMbert_embedder"
  output: /data/cat/ws/alju972f-regression_heads/dataset/mmbet_embeddings/mmber_logs/%j.out
  error: /data/cat/ws/alju972f-regression_heads/dataset/mmbet_embeddings/mmber_logs/%j.err
  qos: "normal"
  venv_path: /data/cat/ws/alju972f-regression_heads/envs/env_regression_heads/bin/activate
  tasks: 10
  workers: 1001
