params:
  glob_pattern: "**/*.h5"
  embeddings_directory: /data/horse/ws/alju972f-tokenization_at_scale/data_ml_filter/embedding/training_embeddings
  output_dir: /data/horse/ws/alju972f-tokenization_at_scale/data_ml_filter/annotations

  regression_head_checkpoints:
    Gemma_Snowflake: /data/horse/ws/alju972f-tokenization_at_scale/data_ml_filter/final_regression_head
    Llama_Snowflake: /data/horse/ws/alju972f-tokenization_at_scale/data_ml_filter/final_regression_head
    Mistral_Snowflake: /data/horse/ws/alju972f-tokenization_at_scale/data_ml_filter/final_regression_head
  batch_size: 1000
  hdf5_dataset_name: fineweb2

  # Metadata key customization
  embedding_key: embeddings
  label_key: labels
  document_id_key: document_ids
  score_prefix: "score_"

  output_keys: [document_ids]
  model_dtype: bfloat16
  embedding_dtype: bfloat16
  label_dtype: bfloat16
  compression: gzip

running_on_slurm: true

local_settings: null

slurm_settings:
  sbatch_args:
    account: "p_gptx"
    nodes: 1
    ntasks: 1
    gres: gpu:1
  partition: "capella"
  time: "04:00:00"
  cpus_per_task: 8
  mem_per_cpu_gb: 2
  job_name: "MMbert_embedder"
  output: /data/cat/ws/alju972f-regression_heads/dataset/mmbet_embeddings/mmber_logs/%j.out
  error: /data/cat/ws/alju972f-regression_heads/dataset/mmbet_embeddings/mmber_logs/%j.err
  qos: "normal"
  venv_path: /data/cat/ws/alju972f-regression_heads/envs/env_regression_heads/bin/activate
  tasks: 1
  workers: 1
