glob_pattern: "*.jsonl"
input_dir: /leonardo_work/EUHPC_D21_101/alexj/repos/ml_filter_outputs/trail_run/input_data_test
output_dir: /leonardo_work/EUHPC_D21_101/alexj/repos/ml_filter_outputs/trail_run/output_dir/new_embeddings
csv_hashmap_path: /leonardo_work/EUHPC_D21_101/alexj/repos/scripts/hashes.csv

embedding_model: Snowflake/snowflake-arctic-embed-m-v2.0
batch_size: 218

hdf5_dataset_name: train

datatrove:
  tasks: 2
  workers: 1001

slurm:
  partition: "boost_usr_prod"
  time: "00:30:00"
  cpus_per_task: 32
  mem_per_cpu_gb: 8
  gpus_per_task: 1
  job_name: "lorem_ipsum_embedding"
  output: /leonardo_work/EUHPC_D21_101/alexj/repos/ml_filter_outputs/trail_run/output_dir/%j.out
  error: /leonardo_work/EUHPC_D21_101/alexj/repos/ml_filter_outputs/trail_run/output_dir/%j.err
  account: "EUHPC_E05_119"
  qos: "normal" #"boost_qos_dbg",
  nodes: 1
  ntasks: 1
  gres: gpu:1
  venv_path: /leonardo_work/EUHPC_D21_101/alexj/repos/scripts/env_backup/venv_test/bin/activate #/leonardo_work/EUHPC_D21_101/alexj/repos/scripts/env/venv_annotation_pipeline/bin/python
