glob_pattern: "*.jsonl"
input_dir: /data/cat/ws/alju972f-annotation_at_scale/data/sample_data
output_dir: /data/cat/ws/alju972f-annotation_at_scale/data/embedding_output_dir
csv_hashmap_path: /data/cat/ws/alju972f-annotation_at_scale/data/embedding_output_dir/scripts/hashes.csv

embedding_model: Snowflake/snowflake-arctic-embed-m-v2.0
batch_size: 1000

hdf5_dataset_name: train


slurm:
  partition: "capella"
  tasks: 1
  workers: 1001
  time: "01:00:00"
  cpus_per_task: 56
  gpus_per_task: 1
  mem_per_gpu: "8G"
  job_name: "lorem_ipsum_embedding"
  output: /data/cat/ws/alju972f-annotation_at_scale/.vscode/data/embedding_output_dir/scripts/slurm_output/%j.out
  error: /data/cat/ws/alju972f-annotation_at_scale/.vscode/data/embedding_output_dir/scripts/slurm_output/%j.err
  account: "p_gptx"
  qos: "normal"
  nodes: 4
  ntasks_per_node: 1
  gres: gpu:4