dataset_name: training

params:
  # File selection
  glob_pattern: "**/*.jsonl"
  input_dir: /raid/s3/opengptx/abbas/processed_data_natural/${dataset_name}_set
  csv_hashmap_path: /raid/s3/opengptx/jude/repos/ml_filter/embedding_ablations/dataset/hashes/${dataset_name}.csv

  # Output
  output_dir: /raid/s3/opengptx/jude/repos/ml_filter/embedding_ablations/mmbert_results/embeddings
  embedding_dir: ${dataset_name}_embeddings

  # Model and embedding parameters
  embedding_model: jhu-clsp/mmBERT-base
  batch_size: 128
  writer_batch_size: 1000
  hdf5_dataset_name: train
  save_labels: true
  max_length: 8192
  padding: true
  truncation: true

running_on_slurm: false

local_settings: null

slurm_settings: 
  partition: "capella"
  tasks: 1
  workers: 1001
  time: "04:00:00"
  cpus_per_task: 32
  mem_per_cpu_gb: 8
  gpus_per_task: 1
  job_name: "MMbert_embedder"
  output: /data/cat/ws/alju972f-regression_heads/dataset/mmbet_embeddings/mmber_logs/%j.out
  error: /data/cat/ws/alju972f-regression_heads/dataset/mmbet_embeddings/mmber_logs/%j.err
  account: "p_gptx"
  qos: "normal"
  nodes: 4
  ntasks: 1
  gres: gpu:4
  venv_path: /data/cat/ws/alju972f-regression_heads/envs/env_regression_heads/bin/activate
