glob_pattern: "**/*.jsonl" #"*.jsonl"
input_dir: /raid/s3/opengptx/jude/repos/ml_filter/data/input_dir_hierarchy #/raid/s3/opengptx/jude/repos/ml_filter/data/input_data
output_dir: /raid/s3/opengptx/jude/repos/ml_filter/data/embedding_output_dir
csv_hashmap_path: /raid/s3/opengptx/jude/repos/ml_filter/data/embedding_output_dir/scripts/hashes.csv

embedding_model: Snowflake/snowflake-arctic-embed-m-v2.0
batch_size: 256
writer_batch_size: 1000

hdf5_dataset_name: train

tasks: 8 # number of tasks
workers: 8 
local_tasks: 8 # number of gpus in a node
local_rank_offset: 0
