experiment_dir_paths:
  - data/output/2024-12-11__14-51-24__4ecfea30
  - data/output/2024-12-11__14-52-17__e06b8c1d
experiment_config_file_name: lorem_ipsum.yaml
output_format:
  - sort_by_metric:  mean_out_tokens_per_second
    ascending: false

