experiment_dir_paths:
  - data/output/2024-12-04__18-05-15__29f6940d
  - data/output/2024-12-04__18-08-49__29f6940d

gold_annotations_file_path: data/dev_data_ml_filter_511_head_100.jsonl
config_file_name: lorem_ipsum.yaml
output_format:
  - sort_by_metric:  mae
    ascending: false
  
