#Points to an endpoint where the model is running

settings:
  model_name: mlabonne/Meta-Llama-3.1-8B-Instruct-abliterated
  tokenizer_name_or_path: ${settings.model_name}
  paths:
    raw_data_file_paths: 
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2014-41/fi/00040.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2014-41/hr/00063.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2014-41/eu/00004.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2014-41/ga/00061.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2019-26/sv/00118.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/bg/01692.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/da/01690.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/da/04285.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/da/04313.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/cs/01255.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/de/00225.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/be/01731.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/be/04749.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/be/03028.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/be/03328.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/be/03947.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/af/03213.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/af/00209.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/af/00786.jsonl
    - /raid/s3/opengptx/max_lue/data_quality_ablations/data_quality_ablations/data/cc_raw_subsets/cc_debug_400_docs/2023-50/af/01365.jsonl
    output_directory_path: data/output
    prompt_template_file_path: data/prompts/fineweb_edu/prompt.yaml

llm_rest_client:
  model_name: ${settings.model_name}
  max_tokens: 4096
  max_new_tokens: 500
  temperature: 0.001
  max_pool_connections: 100
  max_pool_maxsize: 100 #TODO
  max_retries: 2
  backoff_factor: 0.4 
  timeout: 20
  verbose: false

tokenizer:
  pretrained_model_name_or_path: ${settings.tokenizer_name_or_path}
  special_tokens: null

prompt_builder:
  prompt_template_file_path: ${settings.paths.prompt_template_file_path}
  # The maximum length of the prompt
  # Note that the maximum number of generated tokens is
  # model_context_length - max_prompt_length
  max_prompt_length: ${eval:'${llm_rest_client.max_tokens} - ${llm_rest_client.max_new_tokens}'}

document_processor:
  output_directory_path: ${settings.paths.output_directory_path}
  queue_size: 100
  batch_size: 16
  num_processes: 10
  score_metric_name: educational_score

  strings_to_remove: []
