#Points to an endpoint where the model is running

settings:
  model_name: google/gemma-2-9b-it
  # we need to set this here manually as this is specified only when hosting the model
  num_gpus: 1
  tokenizer_name_or_path: ${settings.model_name}
  
  paths:
    raw_data_file_paths: 
    - /raid/s3/opengptx/akhan/ml_filter/data/test_fineweb2_dump.jsonl
    output_directory_path: data/output
    prompt_template_file_path: /raid/s3/opengptx/akhan/ml_filter/data/prompts/fineweb_edu/educational_prompt.yaml
    start_indexes:
    - 10   

llm_rest_client:
  model_name: ${settings.model_name}
  max_tokens: 8192 # The maximum total number of tokens supported by the model (input + output)
  sampling_params:
    max_tokens: 500 # The maximum number of tokens to generate
    temperature: 0.7
    n: 3 # The number of sequences to generate
    top_p: 0.9
  max_pool_connections: 1000
  max_pool_maxsize: 1000 #TODO
  max_retries: 2
  backoff_factor: 0.4 
  timeout: 100
  verbose: false
  num_gpus: ${settings.num_gpus}

tokenizer:
  pretrained_model_name_or_path: ${settings.tokenizer_name_or_path}
  special_tokens: null
  add_generation_prompt: true

prompt_builder:
  prompt_template_file_path: ${settings.paths.prompt_template_file_path}
  # The maximum length of the prompt
  # Note that the maximum number of generated tokens is
  # model_context_length - max_prompt_length
  max_prompt_length: ${eval:'${llm_rest_client.max_tokens} - ${llm_rest_client.sampling_params.max_tokens}'}

document_processor:
  output_directory_path: ${settings.paths.output_directory_path}
  queue_size: 1000
  num_processes: 1
  score_metric_name: educational_score
  strings_to_remove: []
  jq_language_pattern: .metadata.language
