#Points to an endpoint where the model is running
rest_endpoint: http://127.0.0.1:8098/

data:
  input_data:
    path: data/1000_documents_new.jsonl
    split: train

llm_rest_client:
  rest_endpoint: ${rest_endpoint}
  model_name: llama
  max_tokens: 60000
  max_new_tokens: 500
  temperature: 0.001
  max_pool_connections: 100
  max_pool_maxsize: 100 #TODO
  max_retries: 2
  backoff_factor: 0.4 
  timeout: 20
  verbose: false

tokenizer:
  pretrained_model_name_or_path: meta-llama/Meta-Llama-3.1-8B
  special_tokens: null

prompt_builder:
  prompt_path: data/prompts/fineweb_edu/prompt.yaml
  max_prompt_length: 3596

document_processor:
  output_file_path: data/output/lorem_ipsum.jsonl
  queue_size: 10
  batch_size: 2
  num_processes: 3
  score_metric_name: educational_score

  strings_to_remove:
    - "<"
    - "|"
    - "begin_of_text"
    - ">"
    - "<"
    - "|"
    - "start_header_id"
    - "|"
    - ">"
    - "<"
    - "|"
    - "end_header_id"
    - "|"
    - ">"
    - "["
    - "…"
    - "]"
    - "„"
    - "“"
    - "–"
    - "‘"
    - ";"
    - ":"
    - "/"
    - "-"
    - '"'
    - "{"
    - "}"
    - "\\"
    - "”"
    - ")"
    - "("
    - "www."
    - "%"
    - "→"
    - "!"
    - "*"
    - "#"
    - "’"
    - ".."
    - ".com"
    - "[INST]"
    - "</s>"
    - "<s>"
    - ">"
    - "["
    - "…"
    - "]"
    - "„"
    - "“"
    - "–"
    - "‘"
    - ";"
    - ":"
    - "/"
    - "-"
    - '"'
    - "{"
    - "}"
    - "\\"
    - "”"
    - ")"
    - "("
    - "www."
    - "%"
    - "→"
    - "!"
    - "*"
    - "#"
    - "’"
    - ".."
    - ".com"