# Check
EUROPEAN_LANGUAGES = {
    "sq": "Albanian",
    "hy": "Armenian",
    "eu": "Basque",
    "bg": "Bulgarian",
    "hr": "Croatian",
    "ca": "Catalan",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "en": "English",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "gl": "Galician",
    "de": "German",
    "el": "Greek",
    "hu": "Hungarian",
    "is": "Icelandic",
    "ga": "Irish",
    "it": "Italian",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "mk": "Macedonian",
    "mt": "Maltese",
    "nb": "Norwegian Bokmål",
    "nn": "Norwegian Nynorsk",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "sh": "Serbo-Croation",
    "sr": "Serbian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "es": "Spanish",
    "sv": "Swedish",
    "tr": "Turkish",
    "uk": "Ukrainian",
}

DEEPL = "deepl"
OPENAI = "openai"
TARGET_LANGAUGE_PLACEHOLDER = '{##TARGET_LANGUAGE##}'
